// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocksensor

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFetcher creates a new instance of MockFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFetcher {
	mock := &MockFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFetcher is an autogenerated mock type for the Fetcher type
type MockFetcher struct {
	mock.Mock
}

type MockFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFetcher) EXPECT() *MockFetcher_Expecter {
	return &MockFetcher_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockFetcher
func (_mock *MockFetcher) Do(req *http.Request) (*http.Response, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (*http.Response, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFetcher_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockFetcher_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - req *http.Request
func (_e *MockFetcher_Expecter) Do(req interface{}) *MockFetcher_Do_Call {
	return &MockFetcher_Do_Call{Call: _e.mock.On("Do", req)}
}

func (_c *MockFetcher_Do_Call) Run(run func(req *http.Request)) *MockFetcher_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFetcher_Do_Call) Return(response *http.Response, err error) *MockFetcher_Do_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockFetcher_Do_Call) RunAndReturn(run func(req *http.Request) (*http.Response, error)) *MockFetcher_Do_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockFetcher
func (_mock *MockFetcher) Get(url string) (*http.Response, error) {
	ret := _mock.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*http.Response, error)); ok {
		return returnFunc(url)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *http.Response); ok {
		r0 = returnFunc(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFetcher_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockFetcher_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - url string
func (_e *MockFetcher_Expecter) Get(url interface{}) *MockFetcher_Get_Call {
	return &MockFetcher_Get_Call{Call: _e.mock.On("Get", url)}
}

func (_c *MockFetcher_Get_Call) Run(run func(url string)) *MockFetcher_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFetcher_Get_Call) Return(response *http.Response, err error) *MockFetcher_Get_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockFetcher_Get_Call) RunAndReturn(run func(url string) (*http.Response, error)) *MockFetcher_Get_Call {
	_c.Call.Return(run)
	return _c
}
