packages:
  github.com/emiliogozo/panahon-api-go/db/sqlc:
    interfaces:
      Store:
        config:
          dir: "db/mocks"
          filename: "store.go"
          outpkg: "mockdb"
  github.com/emiliogozo/panahon-api-go/internal/sensor:
    interfaces:
      Fetcher:
        config:
          dir: "internal/mocks"
          filename: "fetcher.go"
          outpkg: "mocksensor"
