// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_token.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAPITokensByUser = `-- name: CountAPITokensByUser :one
SELECT COUNT(*) FROM api_tokens
WHERE user_id = $1
`

func (q *Queries) CountAPITokensByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAPITokensByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (
    user_id,
    name,
    token_hash,
    token_prefix,
    permissions,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, name, token_hash, token_prefix, permissions, last_used_at, expires_at, created_at, updated_at
`

type CreateAPITokenParams struct {
	UserID      int64              `json:"user_id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	Permissions []byte             `json:"permissions"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (APIToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Permissions,
		arg.ExpiresAt,
	)
	var i APIToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Permissions,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens
WHERE id = $1
`

func (q *Queries) DeleteAPIToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAPIToken, id)
	return err
}

const getAPIToken = `-- name: GetAPIToken :one
SELECT id, user_id, name, token_hash, token_prefix, permissions, last_used_at, expires_at, created_at, updated_at FROM api_tokens
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAPIToken(ctx context.Context, id int64) (APIToken, error) {
	row := q.db.QueryRow(ctx, getAPIToken, id)
	var i APIToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Permissions,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, name, token_hash, token_prefix, permissions, last_used_at, expires_at, created_at, updated_at FROM api_tokens
WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (APIToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i APIToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Permissions,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPITokensByUser = `-- name: ListAPITokensByUser :many
SELECT id, user_id, name, token_hash, token_prefix, permissions, last_used_at, expires_at, created_at, updated_at FROM api_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAPITokensByUser(ctx context.Context, userID int64) ([]APIToken, error) {
	rows, err := q.db.Query(ctx, listAPITokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []APIToken{}
	for rows.Next() {
		var i APIToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.Permissions,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPITokenLastUsedAt = `-- name: UpdateAPITokenLastUsedAt :exec
UPDATE api_tokens
SET last_used_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateAPITokenLastUsedAt(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateAPITokenLastUsedAt, id)
	return err
}
