// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocktoken

import (
	"time"

	"github.com/emiliogozo/panahon-api-go/internal/token"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMaker creates a new instance of MockMaker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMaker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMaker {
	mock := &MockMaker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMaker is an autogenerated mock type for the Maker type
type MockMaker struct {
	mock.Mock
}

type MockMaker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMaker) EXPECT() *MockMaker_Expecter {
	return &MockMaker_Expecter{mock: &_m.Mock}
}

// CreateToken provides a mock function for the type MockMaker
func (_mock *MockMaker) CreateToken(user token.User, duration time.Duration) (string, *token.Payload, error) {
	ret := _mock.Called(user, duration)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 string
	var r1 *token.Payload
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(token.User, time.Duration) (string, *token.Payload, error)); ok {
		return returnFunc(user, duration)
	}
	if returnFunc, ok := ret.Get(0).(func(token.User, time.Duration) string); ok {
		r0 = returnFunc(user, duration)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(token.User, time.Duration) *token.Payload); ok {
		r1 = returnFunc(user, duration)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*token.Payload)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(token.User, time.Duration) error); ok {
		r2 = returnFunc(user, duration)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMaker_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type MockMaker_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - user token.User
//   - duration time.Duration
func (_e *MockMaker_Expecter) CreateToken(user interface{}, duration interface{}) *MockMaker_CreateToken_Call {
	return &MockMaker_CreateToken_Call{Call: _e.mock.On("CreateToken", user, duration)}
}

func (_c *MockMaker_CreateToken_Call) Run(run func(user token.User, duration time.Duration)) *MockMaker_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 token.User
		if args[0] != nil {
			arg0 = args[0].(token.User)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMaker_CreateToken_Call) Return(s string, payload *token.Payload, err error) *MockMaker_CreateToken_Call {
	_c.Call.Return(s, payload, err)
	return _c
}

func (_c *MockMaker_CreateToken_Call) RunAndReturn(run func(user token.User, duration time.Duration) (string, *token.Payload, error)) *MockMaker_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyToken provides a mock function for the type MockMaker
func (_mock *MockMaker) VerifyToken(token1 string) (*token.Payload, error) {
	ret := _mock.Called(token1)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 *token.Payload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*token.Payload, error)); ok {
		return returnFunc(token1)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *token.Payload); ok {
		r0 = returnFunc(token1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token.Payload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMaker_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type MockMaker_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//   - token1 string
func (_e *MockMaker_Expecter) VerifyToken(token1 interface{}) *MockMaker_VerifyToken_Call {
	return &MockMaker_VerifyToken_Call{Call: _e.mock.On("VerifyToken", token1)}
}

func (_c *MockMaker_VerifyToken_Call) Run(run func(token1 string)) *MockMaker_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMaker_VerifyToken_Call) Return(payload *token.Payload, err error) *MockMaker_VerifyToken_Call {
	_c.Call.Return(payload, err)
	return _c
}

func (_c *MockMaker_VerifyToken_Call) RunAndReturn(run func(token1 string) (*token.Payload, error)) *MockMaker_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}
