// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocksensor

import (
	"github.com/emiliogozo/panahon-api-go/internal/sensor"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDavisSensor creates a new instance of MockDavisSensor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDavisSensor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDavisSensor {
	mock := &MockDavisSensor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDavisSensor is an autogenerated mock type for the DavisSensor type
type MockDavisSensor struct {
	mock.Mock
}

type MockDavisSensor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDavisSensor) EXPECT() *MockDavisSensor_Expecter {
	return &MockDavisSensor_Expecter{mock: &_m.Mock}
}

// FetchLatest provides a mock function for the type MockDavisSensor
func (_mock *MockDavisSensor) FetchLatest() ([]sensor.DavisCurrentObservation, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchLatest")
	}

	var r0 []sensor.DavisCurrentObservation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]sensor.DavisCurrentObservation, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []sensor.DavisCurrentObservation); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sensor.DavisCurrentObservation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDavisSensor_FetchLatest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchLatest'
type MockDavisSensor_FetchLatest_Call struct {
	*mock.Call
}

// FetchLatest is a helper method to define mock.On call
func (_e *MockDavisSensor_Expecter) FetchLatest() *MockDavisSensor_FetchLatest_Call {
	return &MockDavisSensor_FetchLatest_Call{Call: _e.mock.On("FetchLatest")}
}

func (_c *MockDavisSensor_FetchLatest_Call) Run(run func()) *MockDavisSensor_FetchLatest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDavisSensor_FetchLatest_Call) Return(davisCurrentObservations []sensor.DavisCurrentObservation, err error) *MockDavisSensor_FetchLatest_Call {
	_c.Call.Return(davisCurrentObservations, err)
	return _c
}

func (_c *MockDavisSensor_FetchLatest_Call) RunAndReturn(run func() ([]sensor.DavisCurrentObservation, error)) *MockDavisSensor_FetchLatest_Call {
	_c.Call.Return(run)
	return _c
}
